apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/suricata/*.log
      fields:
        service: suricata
      fields_under_root: true
      ignore_older: 24h

    - type: log
      paths:
        - /var/log/modsec_audit.log
      fields:
        service: modsecurity
      fields_under_root: true
      ignore_older: 24h

    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}"]
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      indices:
        - index: "filebeat-modsecurity-%{+yyyy.MM.dd}"
          when.equals:
            service: "modsecurity"
        - index: "filebeat-suricata-%{+yyyy.MM.dd}"
          when.equals:
            service: "suricata"
        - index: "filebeat-%{+yyyy.MM.dd}"
          when.equals:
            service: null

    setup.kibana:
      host: "${KIBANA_HOST:kibana}:${KIBANA_PORT:5601}"

    setup.template.name: "filebeat"
    setup.template.pattern: "filebeat-*"
    setup.ilm.enabled: false
