apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk-system
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.0
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "choa0306@@"
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
          value: "none"
        - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
          value: "c34d38b3a14956121ff2170e5030b471551370178f43e5626eec58b04a30fae2"
        - name: XPACK_REPORTING_ENCRYPTIONKEY
          value: "c34d38b3a14956121ff2170e5030b471"
        - name: XPACK_SECURITY_ENCRYPTIONKEY
          value: "c34d38b3a14956121ff2170e5030b471"
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk-system
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch:9200"]
    elasticsearch.username: "elastic"
    elasticsearch.password: "choa0306@@"
    xpack.security.enabled: true
    elasticsearch.ssl.verificationMode: none
    xpack.encryptedSavedObjects.encryptionKey: "c34d38b3a14956121ff2170e5030b471551370178f43e5626eec58b04a30fae2"
    xpack.reporting.encryptionKey: "c34d38b3a14956121ff2170e5030b471"
    xpack.security.encryptionKey: "c34d38b3a14956121ff2170e5030b471"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk-system
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30601
