apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aurora
  template:
    metadata:
      labels:
        app: aurora
    spec:
      nodeSelector:
        node-type: webservice
      containers:
      - name: aurora
        image: krjaeh0/aurora:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aurora-service
spec:
  type: NodePort
  selector:
    app: aurora
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
